#cloud-config

# On met à jour le système
package_update: false
package_upgrade: false

# On créé l'utilisateur avec droits sudo en précisant sa clé SSH publique
users:
   - default
   - name: ue5
     shell: /bin/bash
     sudo: ['ALL=(ALL) NOPASSWD:ALL']

# On créé le docker group
groups:
  - docker: [ue5, sudo]

#packages:
#  - blender
#  - curl

# No more useful because exported in runcmd
write_files:
  - path: /etc/profile.d/secret.sh
    content: |
         # RUNNER_CFG_PAT (The PAT Token) is replaced by the github action
         export RUNNER_CFG_PAT=$RUNNER_CFG_PAT

# Stop github runner at shutdown
write_files:
  - path: /etc/rc0.d/K99-gh-runner
    content: |
         export RUNNER_CFG_PAT=$RUNNER_CFG_PAT
         curl -s https://raw.githubusercontent.com/actions/runner/main/scripts/remove-svc.sh | bash -s twin-city/unreal-project

runcmd:
  # On télécharge le package des github runners
  # https://github.com/actions/runner/blob/main/docs/automate.md
  - sudo chmod 666 /var/run/docker.sock
  - 'mkdir -p /home/ue5/.ssh'
  - 'cp /root/.ssh/authorized_keys /home/ue5/.ssh/authorized_keys'
  - 'chown ue5 /home/ue5/.ssh/authorized_keys'
  # On se place dans le dossier de l'utilisateur
  - cd /home/ue5
  - export RUNNER_CFG_PAT=$RUNNER_CFG_PAT
  - curl -s https://raw.githubusercontent.com/actions/runner/main/scripts/create-latest-svc.sh | bash -s -- -s twin-city/unreal-project -n scw-runner -u ue5 -l unreal

final_message: "Le système est configuré. Délai nécessaire : $UPTIME secondes"

power_state:
  timeout: 120
  delay: "+57"
  message: Shutdown in one hour. Please save your work.
  mode: poweroff
  condition: true
