#cloud-config

# On met à jour le système
package_update: false
package_upgrade: false

# On créé l'utilisateur avec droits sudo en précisant sa clé SSH publique
users:
   - default
   - name: ue5
     shell: /bin/bash
     sudo: ['ALL=(ALL) NOPASSWD:ALL']
#packages:
#  - blender
#  - curl

write_files:
  - path: /etc/profile.d/secret.sh
    content: |
         # RUNNER_CFG_PAT (The PAT Token) is replaced by the github action
         export RUNNER_CFG_PAT=$RUNNER_CFG_PAT

runcmd:
  # On télécharge le package des github runners
  # https://github.com/actions/runner/blob/main/docs/automate.md
  - 'mkdir -p /home/ue5/.ssh'
  - 'cp /root/.ssh/authorized_keys /home/ue5/.ssh/authorized_keys'
  - 'chown ue5 /home/ue5/.ssh/authorized_keys'
  # On se place dans le dossier de l'utilisateur
  - cd /home/ue5
  - export RUNNER_CFG_PAT=$RUNNER_CFG_PAT
  - curl -s https://raw.githubusercontent.com/actions/runner/main/scripts/create-latest-svc.sh | bash -s -- -s twin-city/unreal-project -n scw-runner -u ue5

  #- git clone https://github.com/twin-city/unreal-project
  # On télécharge les fichiers de travail
  #- wget https://download.blender.org/demo/test/benchmark.zip

final_message: "Le système est configuré. Délai nécessaire : $UPTIME secondes"

power_state:
  timeout: 120
  delay: "+5"
  message: Shutdown in five minutes. Please save your work.
  mode: shutdown
